# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_comentarios_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
