# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20160927_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='comentario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Comentarios'),
        ),
    ]
