# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20160927_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.Eventos'),
            preserve_default=False,
        ),
    ]
