# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20160927_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Eventos'),
        ),
    ]
