# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20160928_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='evento',
            field=models.TextField(),
        ),
    ]
