# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0017_auto_20160928_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaComentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Comentarios')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Eventos')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
