# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_auto_20160929_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.RespostaComentarios'),
        ),
    ]
