# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_remove_respostacomentarios_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostacomentarios',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
