# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_respostacomentarios_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(default='lala.jpg', upload_to=''),
        ),
    ]
