# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_auto_20161002_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='img',
        ),
        migrations.AddField(
            model_name='eventos',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventos',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventos',
            name='valor',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
