# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_auto_20161002_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.ImageField(default='lala', upload_to=''),
        ),
    ]
