# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_auto_20161002_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
