# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_auto_20161004_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='estilos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='hora',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='valor',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
