# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_auto_20161004_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='data',
            field=models.CharField(default=0.0009000900090009, max_length=10),
            preserve_default=False,
        ),
    ]
