# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0034_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
