# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0036_eventos_num_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='img_link',
            field=models.TextField(default='http://pcswired.com/headsetperson35.png'),
        ),
    ]
